### ISSUE TITLE
Add a way to edit a subject's offerings

### ISSUE THREAD

**Issue by Yivan000** [tudlang/araltools#29]
Blocks #13.

**Comment by jerichosy** [comment]
Not sure if this should be a new issue, but I'd like it if this feature was extended to have some sort of toggle all option. My current use case is for GEs where there could be 50 offerings and I want to only "check" those coming from a particular prof. But to do that ideally, I would want to "uncheck" everything else first.

**Comment by Yivan000** [comment]
@jerichosy That can be dissected into multiple issues.

- #45 
- #34
