### ISSUE TITLE
Use checkboxes to select/unselect sections per subject that will be part of the generation pool

### ISSUE THREAD

**Issue by jerichosy** [tudlang/araltools#39]
In addition to filters, may I suggest adding checkboxes to each course offering so we can fine tune the classes we want to be in the pool for the weekly generation? Something like what SchedNinja.com does (when it still used to work):
![image](https://github.com/tudlang/araltools/assets/69558553/4aebaa81-d39b-4a7c-b9a0-d00aee22bd18)

This is easier for the user to do than `excludeSectionLetter`.

This also helps with the intention of #34

**Comment by Yivan000** [comment]
I believe this is already implemented as per #29 (and will be part of the next update), since you can now toggle the status of an offering whether closed or open.

**Comment by Yivan000** [comment]
Closing this since you can now already do that by toggling the status.
