### ISSUE TITLE
Course schedule/time may be different depending on the day, but app does not show/support this

### ISSUE THREAD

**Issue by jerichosy** [tudlang/araltools#40]
I'm not sure if this is a UI bug or if the app does not actually note down the time for each day the subject is scheduled.
![image](https://github.com/tudlang/araltools/assets/69558553/a70dbf7d-ac20-4a87-b3d4-1e1c95f6e9d4)

**Comment by Yivan000** [comment]
Oh my, I thought that the time will just be the same for M&H, T&F, and W&S offerings. I didn't know this is not always the case. Thank you for making this issue!
