### ISSUE TITLE
Sometimes, when generating, `SchedulesFragmentTimetable` gets horizontally duplicated, causing lag & crashes

### ISSUE THREAD

**Issue by Yivan000** [tudlang/araltools#42]
I have no idea what is causing this error to occur on AralTool's end, but I suspect it has something to do with `fluent_ui`'s TabView.

If you experienced this issue, please comment below the steps that you did that led this to happen.

**Comment by jerichosy** [comment]
Not able to consistently reproduce this. Sometimes it happens and other times it doesn't even if I recreated the same steps. I do notice that once it duplicates, the duplication persists even after repeated generation, sometimes alternating between 2 or 3 rows of `SchedulesFragmentTimetable` in total.

**Comment by Yivan000** [comment]
I think [this StackOverflow question](https://stackoverflow.com/questions/47198533/failed-assertion-line-3927-pos-14-dependents-isempty-is-not-true) may be relevant to this bug. I have attempted to fix it in the above commit.

**Comment by Yivan000** [comment]
Unless this surfaces again, this is now fixed as of 0.2.1.
