### ISSUE TITLE
Gray screen whenever I open a saved file

### ISSUE THREAD

**Issue by dayview** [tudlang/araltools#50]
![sdwdwqd](https://github.com/tudlang/araltools/assets/131971014/b5c70928-1beb-4f87-844d-a0f136f5356d)

After opening a saved file, the app no longer displays anything, and exits normally to save the opened file.

**Comment by dayview** [comment]
Still the same problem.

**Comment by Yivan000** [comment]
This is really odd. I cannot reproduce this issue. 

Is your file is not corrupted? 

Rename the `.atsm` file extension into a `.zip`, and open it in a file compression program (e.g. WinRar, WinZip, 7Zip, etc.). SkedMaker files are basically just `.zip` files under the hood, and so these programs can see what's inside.

If it cannot open the file, then most likely the file itself is corrupt, and the software is fine.

**Comment by dayview** [comment]
Hi Yivan! It's fixed now. Thanks for the help!

**Comment by Yivan000** [comment]
\O/
